- name: Build docs
  shell: >
        . {{ voeventcache_venv }}/bin/activate &&
        rm -rf {{ wwwroot }}/docs/* &&
        sphinx-build -b html  -v source {{ wwwroot }}/docs

  args:
    chdir: "{{ voeventcache_repo_path }}/docs"
  become: yes
  become_user: "{{ voeventcache_user }}"
  changed_when: False