---
# tasks file for voeventdb
- name: Install apt dependencies.
  apt: name={{item}} update_cache=yes cache_valid_time=600
  with_items: "{{ lookup('file', 'voeventdb-apt-deps.txt').split() }}"
  sudo: yes
  tags: apt

- include: users.yml tags=users
- include: postgres_setup.yml tags=postgres
- include: voeventdb_install.yml tags=install
- include: rest_server_setup.yml tags=apache
  when: rest_enabled
- include: docs_build.yml tags=docs
  when: rest_enabled
- include: rest_server_deactivate.yml tags=apache
  when: not rest_enabled

