---
# tasks file for voeventdb
- name: Install voeventdb apt dependencies.
  apt: name={{item}} update_cache=yes cache_valid_time=600
  with_items: "{{ lookup('file', 'voeventdb-apt-deps.txt').split() }}"
  sudo: yes
  tags: apt

- name: Install Apache apt dependencies
  apt: name={{item}} update_cache=yes cache_valid_time=600
  with_items: "{{ lookup('file', 'apache-apt-deps.txt').split() }}"
  sudo: yes
  when: voeventdb_rest_enabled
  tags: apt, apache


- include: users.yml
  tags: users

- include: postgres_setup.yml
  tags: postgres

- include: voeventdb_install.yml
  tags: install

- include: rest_server_setup.yml
  tags: apache
  when: voeventdb_rest_enabled

- include: docs_build.yml
  tags: docs
  when: voeventdb_rest_enabled

- include: rest_server_deactivate.yml
  tags: apache
  when: not voeventdb_rest_enabled

