---
# tasks file for voeventcache
- name: Install apt dependencies.
  apt: name={{item}} update_cache=yes cache_valid_time=600
  with_items: "{{ lookup('file', 'voeventcache-apt-deps.txt').split() }}"
  sudo: yes
  tags: apt

- include: users.yml tags=users
- include: postgres_setup.yml tags=postgres
- include: voeventcache_install.yml tags=install
- include: rest_server_setup.yml tags=apache

