- name: Drop in readymade postgres.conf
  copy:
    src: postgresql.conf-9.3
    dest: /etc/postgresql/9.3/main
    mode: "u=rw,g=r,o=r"
  sudo: yes
  #Restart service if invocation has changed:
  notify:
    - restart postgres

- name: Create postgres voeventdb user
  postgresql_user:
    name: "{{voeventdb_user}}"
    password: "{{voeventdb_user}}"
    role_attr_flags: "CREATEDB"
  become: yes
  become_user: postgres

- name: Create postgres voeventdb read-only user
  postgresql_user:
    name: "{{voeventdb_ro_user}}"
    password: "{{voeventdb_ro_user}}"
  become: yes
  become_user: postgres

- name: Create postgres user-db (simplifies use of default login)
  postgresql_db:
    name: "{{voeventdb_user}}"
    login_user: "{{voeventdb_user}}"
  become: yes
  become_user: "{{voeventdb_user}}"


