- name: Ensure UTC timezone
  lineinfile:
    path: /etc/postgresql/10/main/postgresql.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.subst }}"
    backup: yes
  with_items:
    - { regexp: '^timezone', subst: "timezone = 'UTC'" }
    - { regexp: '^log_timezone', subst: "log_timezone = 'UTC'" }
  become: yes
  #Restart service if invocation has changed:
  notify:
    - restart postgres

- name: Create postgres voeventdb user
  postgresql_user:
    name: "{{ voeventdb_rw_user }}"
    password: "{{ voeventdb_rw_user }}"
    role_attr_flags: "SUPERUSER" #NB must be superuser for successful q3c init.
    encrypted: yes
  become: yes
  become_user: "postgres"

- name: Create postgres voeventdb read-only user
  postgresql_user:
    name: "{{voeventdb_ro_user}}"
    password: "{{voeventdb_ro_user}}"
    encrypted: yes
  become: yes
  become_user: "postgres"

- name: Create default-database for voeventdb_owner  (simplifies login)
  postgresql_db:
    name: "{{ voeventdb_rw_user }}"
    login_user: "{{ voeventdb_rw_user }}"
  become: yes
  become_user: "{{ voeventdb_rw_user }}"


