- name: Enable mod_wsgi
  apache2_module: state=present name={{item}}
  with_items:
    - wsgi
    - rewrite
  become: yes
  notify: restart apache

- name: Disable default siteconf
  command: a2dissite 000-default
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  become: yes
  #Restart service if init-script has changed:
  notify:
    - restart apache

- name: Create /var/www subdir with correct permissions
  file: path={{item}} state=directory mode=0755 owner={{ voeventdb_rw_user }}
  with_items:
    - "{{ wwwroot }}"
  become: yes

- name: Upload templated voeventdb wsgi config
  template:
    src: voeventdb.wsgi.j2
    dest: "{{ wwwroot }}/voeventdb.wsgi"
    owner: "{{ voeventdb_rw_user }}"
    group: "{{ voeventdb_group }}"
    mode: "u=rw,g=r,o=r"
  become: yes
  #Restart service if init-script has changed:
  notify:
    - restart apache


- name: Upload templated voeventdb site conf
  template:
    src: voeventdb_site.conf.j2
    dest: "/etc/apache2/sites-available/voeventdb_site.conf"
    owner: root
    mode: "u=rw,g=r,o=r"
  become: yes
  #Restart service if init-script has changed:
  notify:
    - restart apache

- name: Enable voevent siteconf
  command: a2ensite voeventdb_site
  args:
    creates: /etc/apache2/sites-enabled/voeventdb_site.conf
  become: yes
  #Restart service if init-script has changed:
  notify:
    - restart apache