- name: Disable voevent siteconf
  command: a2dissite voeventdb_site
  args:
    removes: /etc/apache2/sites-enabled/voeventdb_site.conf
  become: yes
  register: voeventdb_siteconf_removed

- name: Restart apache if voeventdb removed
  debug: msg="voeventdb_site.conf removed, will notify apache-restart"
  when: voeventdb_siteconf_removed is changed
  notify:
    - restart apache