- name: Create repo / venv dir with correct permissions
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
    owner: "{{ voeventdb_deploy_user }}"
    group: "{{ voeventdb_deploy_user }}"
#    recurse: true
  with_items:
    - "{{ voeventdb_repo_path }}"
    - "{{ voeventdb_venv }}"
  become: yes

- name: "Clone voeventdb repo at version {{ voeventdb_version }}"
  git:
    repo: https://github.com/timstaley/voeventdb.git
    dest: "{{ voeventdb_repo_path }}"
    force: yes
    version: "{{ voeventdb_version }}"
  become: yes
  become_user: "{{ voeventdb_deploy_user }}"
  register: voeventdb_repo_clone_result

- name: Make q3c postgres extension
  command: make install
  args:
    chdir: "{{ voeventdb_repo_path }}/external/q3c"
    creates: "/usr/share/postgresql/9.3/contrib/q3c.sql"
  become: yes

- name: Clean q3c submodule directory
  shell: git clean -df && git reset --hard
  args:
    chdir: "{{ voeventdb_repo_path }}/external/q3c"
#    removes: "{{ voeventdb_repo_path }}/external/q3c/q3c.o"
  become: yes
  become_user: "{{ voeventdb_deploy_user }}"
  changed_when: False

- name: Install voeventdb into v-env
  pip:
    name: ".[all]"
#    extra_args: "-e"
    state: latest
    chdir: "{{ voeventdb_repo_path }}"
    virtualenv: "{{ voeventdb_venv }}"
  when: voeventdb_repo_clone_result | changed
  become: yes
  become_user: "{{ voeventdb_deploy_user }}"

- name: Notify restart-apache if REST enabled and voeventdb updated
  debug: msg="voeventdb updated, will notify apache-restart"
  when: voeventdb_rest_enabled and voeventdb_repo_clone_result | changed
  changed_when: True
  notify:
    - restart apache

- name: Install doc-requirements into v-env
  pip:
    requirements: "docs/requirements.txt"
    chdir: "{{ voeventdb_repo_path }}"
    virtualenv: "{{ voeventdb_venv }}"
  become: yes
  become_user: "{{ voeventdb_deploy_user }}"

- name: Create the corpusdb
  shell: ". {{ voeventdb_venv }}/bin/activate && voeventdb_create.py"
  become: yes
  become_user: "{{ voeventdb_rw_user }}"
  changed_when: False
  tags: test

- name: Run the tests
  shell:
        . {{ voeventdb_venv }}/bin/activate &&
        VOEVENTDB_DEPLOY=1 ./runtests.py -svx
  args:
    chdir: "{{ voeventdb_repo_path }}"
  become: yes
  become_user: "{{ voeventdb_rw_user }}"
  changed_when: False
  register: pytest_result
  failed_when: "'FAILURE' in pytest_result.stdout or 'ERROR' in pytest_result.stdout"
  tags: test

- name: Create the cachedb
  shell: >
        . {{ voeventdb_venv }}/bin/activate &&
          voeventdb_create.py {{ voeventdb_dbname }}
  args:
    chdir: "{{ voeventdb_repo_path }}"
  become: yes
  become_user: "{{ voeventdb_rw_user }}"
  changed_when: False

- name: Grant read-only privs for REST-server on voeventdb DB
  postgresql_privs:
    db: "{{ voeventdb_dbname }}"
    privs: SELECT
    objs: ALL_IN_SCHEMA
    type: table
    schema: public
    roles: "{{ voeventdb_ro_user }}"
    login: "{{ voeventdb_rw_user }}"
  become: yes
  become_user: "{{ voeventdb_rw_user }}"


