# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.define "voeventcachevm" do |voeventcachevm| end

  config.vm.provider "virtualbox" do |v|
      v.memory = 1048
      v.cpus = 2
  end

config.vm.provision "ansible" do |ansible|
   ansible.playbook = "../tests/test-voeventcache-role.yml"
   ansible.verbose = "vv"
end
 
  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
  end
end
