---
# handlers file for voeventdb

- name: restart postgres
  systemd: name=postgresql state=restarted
  become: yes

- name: restart apache
  systemd: name=apache2 state=restarted enabled=yes
  become: yes
